name: 'master_build'
on:
  push:
    branches: [ master ]

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build & Test
    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Check version
        if: github.event_name != 'pull_request'
        id: version-check
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version: $VERSION"
          if [[ "$VERSION" =~ -SNAPSHOT$ ]]; then
            echo "⚠️ Version is snapshot: $VERSION - skipping publish"
            echo "should_publish=false" >> $GITHUB_OUTPUT
            VERSION=latest
          else
            echo "✅ Version is not a snapshot: $VERSION - will publish"
            echo "should_publish=true" >> $GITHUB_OUTPUT
          fi

      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "ossrh-staging-api",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_PASSWORD }}"
            },
            {
              "id": "sonatype-nexus-staging",
              "username": "${{ secrets.OSS_USERNAME }}",
              "password": "${{ secrets.OSS_PASSWORD }}"
            }]
      - name: Build
        if: steps.version-check.outputs.should_publish == 'false'
        run: >
          ./mvnw verify
          -Dspring.rabbitmq.host=localhost
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -U -B $MAVEN_OPTS

      - name: Build & Deploy
        if: steps.version-check.outputs.should_publish == 'true'
        run: >
          ./mvnw deploy
          -Dspring.rabbitmq.host=localhost
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -U -B -Prelease $MAVEN_OPTS

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Sonar
        run: >
          ./mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
          -Dsonar.login=$SONAR_TOKEN
          -Dci.buildNumber=$GITHUB_RUN_NUMBER
          -B $MAVEN_OPTS
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
